swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /document:
    x-swagger-router-controller: document
    post:
      tags: 
      - documents
      summary: Uploads a document
      description: Uploads a document
      operationId: saveFile
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: true
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  /document/{documentHash}:
    x-swagger-router-controller: document
    get:
      tags: 
      - "documents"
      summary: Gets a document by its hash
      description: Gets a document from IPFS using its hash
      operationId: getFile
      produces:
      - application/pdf
      - image/jpeg
      parameters:
      - name: documentHash
        in: path
        description: Document hash
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: file
  /hash:
    x-swagger-router-controller: document
    post:
      tags: 
      - "documents"
      summary: HAHA
      description: HAHA
      operationId: saveHash
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: body
          name: hash
          description: Etwas
          required: true
          schema:
            $ref: "#/definitions/Hash"
      responses:
        200:
          description: OK
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Hash:
    properties:
      hash:
        type: string
  ApiResponse:
    properties:
      transaction:
        type: object
        properties:
          tx:
            type: string
          hash:
            type: string